# Generated by Django 3.1.7 on 2021-03-19 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture_url', models.CharField(max_length=500)),
                ('specialization', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('summary', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(max_length=150)),
                ('position_summary', models.TextField(max_length=1000)),
                ('responsibilities', models.TextField(max_length=2000)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=150)),
                ('topic_summary', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Passions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passion', models.CharField(max_length=100)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('fluency', models.CharField(max_length=50)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('name_of_institution', models.CharField(max_length=300)),
                ('speciality', models.CharField(max_length=100)),
                ('covered_subjects', models.TextField(max_length=1000)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplishment', models.TextField(max_length=500)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_info.personalinformation')),
            ],
        ),
    ]
